path_to_data: /Users/mohamedgabr/Documents/NeuralDialectDetector/NeuralDialectDetector/dataset_dummy
checkpointing_path: /Users/mohamedgabr/Documents/NeuralDialectDetector/NeuralDialectDetector/checkpoints
model_name_path: "bashar-talafha/multi-dialect-bert-base-arabic"
batch_size: 8
classif_dropout_rate: 0.1
initial_learning_rate: 0.00001
adam_epsilon: 1.0e-08
warmup_steps: 500
num_epochs: 1
device: "cpu" # Choose between cpu and cuda
save_final_model: true
checkpointing_on: false
checkpointing_freq: 500 # Needs the argument above to be true
checkpoint_on_improvement: false
improvement_check_freq: 100 # Needs the argument above to be true
seed_list: [1033, 611, 520, 300, 760]