run_title: baseline_5
path_to_data: /home/mohamedgabr/NeuralDialectDetector/NADI2021_DEV.1.0/Subtask_1.2+2.2_DA
checkpointing_path: /home/mohamedgabr/NeuralDialectDetector/checkpoints_baseline
model_name_path: "bashar-talafha/multi-dialect-bert-base-arabic"
model_class: ArabicDialectBERTMaskedLM # Or ArabicDialectBERT
masking_percentage: 0.1 # Applies when training w MLM
batch_size: 16 # 64
classif_dropout_rate: 0.1
initial_learning_rate: 3.75e-5
adam_epsilon: 1.0e-08
warmup_steps: 500
num_epochs: 3 # 10
early_stopping: true
early_stopping_patience: 20
device: cuda # Choose between cpu and cuda
save_final_model: true
checkpointing_on: false
checkpointing_freq: 20 # Needs the argument above to be true
checkpoint_on_improvement: true
improvement_check_freq: 20 # Needs the argument above to be true
seed_list: [1033, 611, 520, 300, 760]
# seed_list: [760]
neptuneaiAPI: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vdWkubmVwdHVuZS5haSIsImFwaV91cmwiOiJodHRwczovL3VpLm5lcHR1bmUuYWkiLCJhcGlfa2V5IjoiYzNlOTI4MDUtMWEwMC00N2U3LWEzYTAtZjAyMzA2YzE1YjI3In0=
neptune_experiment_name: "first_trials_after_fix"